"""ICacheService — abstract port for caching."""
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any


class ICacheService(ABC):
    @abstractmethod
    async def get(self, key: str) -> str | None: ...
    @abstractmethod
    async def set(self, key: str, value: str, ttl: int | None = None) -> None: ...
    @abstractmethod
    async def get_json(self, key: str) -> dict | list | None: ...
    @abstractmethod
    async def set_json(self, key: str, value: dict | list, ttl: int | None = None) -> None: ...
    @abstractmethod
    async def delete(self, key: str) -> None: ...
    @abstractmethod
    async def exists(self, key: str) -> bool: ...
    @abstractmethod
    async def publish_json(self, channel: str, payload: dict) -> int: ...
    @abstractmethod
    async def cache_job_status(self, job_id: str, status: str, progress: int, step: str, extra: dict | None = None) -> None: ...
    @abstractmethod
    async def get_job_status(self, job_id: str) -> dict: ...
    @abstractmethod
    async def invalidate_insights(self, dataset_id: str) -> None: ...
    @abstractmethod
    async def ping(self) -> bool: ...
